# 语言设置
Locale: zh_CN

Debug: false

# 附魔瓶经验值倍率
ExpBottleRatio: 1.0

# 合并经验球
CombineExpOrbs:
  Enable: false
  Radius: 1.5

# 经验吸收无冷却
NoExpCoolDown: false

# 扩展合成表
Recipes:
  CrowBar: true                 # 撬棍
  InvisibleItemFrame: true      # 隐形（发光）物品展示框
  LightBlock: true              # 光源方块
  StackedEnchantBook: true      # 附魔书堆叠

# 把楼梯当作椅子使用
Chair:
  Enable: true
  MaxWidth: 4
  SignCheck: false
  SitHeight: -0.95

# 传送
Teleport:
  Delay: 0            # 传送延迟 秒
  CoolDown: 0         # 冷却时间 秒
  RtpCoolDown: 0      # /rtp 独立冷却时间 秒
  TpaExpire: 30       # 传送请求有效期 秒
  RtpRadius: 1000     # 随机传送最大半径
  log-player-teleport: false # 记录本插件触发的玩家传送日志
  WorldBlackList: [ ] # 不允许传送的世界

# home 相关限制
HomeLimit:
  Amount: 5             # 数量限制
  WorldBlackList: [ ]   # 不允许设置 home 的世界

# 隐身功能
vanish:
  # 是否在玩家游戏模式不同于服务器默认游戏模式时强制开启隐身，有助于管理隐藏
  force-in-different-gamemode: false
  # 增强隐身方案，底层数据包级拦截，防止作弊客户端获取到隐身玩家信息。需安装 ProtocolLib。
  enhanced-mode: false
  # 是否拦截向已隐身玩家发送的常见私聊命令（如 /msg /tell /w）
  block-private-message-to-vanished: false
  # 在隐身时关闭碰撞，防止推动实体
  disable-collidable: true
  # 是否允许隐身玩家攻击玩家，关闭后将禁止隐身玩家攻击所有玩家
  allow-vanisher-attack-player: true
  # 隐身玩家打开带开合动画的容器时，是否改为无动画打开
  cancel-container-animation: false

# 聊天功能已拆分到 chat.yml
# 使用 /essd reload chat 单独重载聊天配置

command-manager:
  Enable: false
  # 拥有 essd.bypass.CommandCD 权限可以绕过此限制
  cooldown: 1000 # 毫秒 (1s=1000ms)
  # 禁止所有玩家执行的一级命令，仅控制台可执行
  # 这里只填主命令名，不要带 /
  banned_command:
    - "op"
    - "deop"

Creative-ItemTake:
  banned-item:
    - "BARRIER"
  banned-nbt: false

# 数据库配置
Database:
  Type: sqlite          # pgsql, sqlite
  Host: localhost       # 数据库地址
  Port: 5432            # 数据库端口
  Name: essentials_d    # 数据库名称
  User: essentials_d    # 数据库用户名
  Pass: essentials_d    # 数据库密码
